[package]
name = "marzban_api"
version = "0.1.0"
edition = "2021"
authors = ["nulluser0 <diuyueng@gmail.com>"]

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
validator = { version = "0.18.1", features = ["derive"] }
